### ISSUE TITLE
Reset_button part has bug

### ISSUE THREAD

**Issue by Zoz4** [Zoz4/Kloski#13]
### 遇到的问题：

Reset后不能正确显示白色方块位置

### 重现步骤：

游戏进行时，移动几步，让白色方块不在原来位置

### 报错信息：
无

**Comment by Zoz4** [comment]
大概是在Reset方块status_matrix时，没有Reset null_digit_no

**Comment by Zoz4** [comment]
> 大概是在Reset方块status_matrix时，没有Reset null_digit_no

已修复

**Comment by Tomspiano** [comment]
status列表也需要更新，具体可查看分支origin/wgw中最新的commit #12
